version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run: python -m pip install .[dev] --user
      - run: python -m pytest -v
      - run: cd docs && make doctest
